export interface LineItemInterface {
  partName: string;
  quantity: number;
  technology:
    | 'CNC machining'
    | '3D printing'
    | 'Urethane casting'
    | 'Sheet metal'
    | 'Injection molding'
    | 'Die casting';
  material:
    | 'Polypropylene'
    | 'PPSU'
    | 'Invar'
    | 'FR4'
    | 'Nickel alloy'
    | 'Tool steel'
    | 'POM (Delrin/Acetal)'
    | 'PBT'
    | 'Steel'
    | 'Titanium'
    | 'Mild steel'
    | 'POM'
    | 'Magnesium'
    | 'PMMA'
    | 'PPE/PS'
    | 'PET'
    | 'Polystyrene'
    | 'LDPE'
    | 'HDPE'
    | 'PMMA (Acrylic)'
    | 'Polyethylene'
    | 'Nylon (MJF)'
    | 'Nylon'
    | 'PEI'
    | 'Stainless steel'
    | 'Alloy steel'
    | 'Resin'
    | 'Copper'
    | 'PSU'
    | 'PTFE (Teflon)'
    | 'Polycarbonate'
    | 'Phosphor Bronze PB102'
    | 'G-10'
    | 'Inconel'
    | 'TPU'
    | 'PLA'
    | 'Cobalt-chrome'
    | 'PC'
    | 'Aluminum'
    | 'CPVC'
    | 'Carbon fiber'
    | 'Polyurethane'
    | 'Nylon (SLS)'
    | 'PVC'
    | 'PETG'
    | 'Nylon (FDM)'
    | 'ABS'
    | 'Brass'
    | 'PS'
    | 'ASA'
    | 'PC/ABS'
    | 'PEEK';
  finish:
    | 'Anodized type III (Hardcoat)'
    | 'Bead Blasted + Chromate Conversion Coating'
    | 'Smooth machining (Ra 1.6μm / Ra 63μin)'
    | 'D-2 | Medium Blast Finish, Blast #240 Oxide (Ra 1.0-2.8)'
    | 'D-1 | Fine Blast Finish, Glass Bead #11 (Ra 0.80-1.00)'
    | 'B-3 | Fine Brush Finish, 320 Grit Paper (Ra 0.28-0.32)'
    | 'Standard (Default)'
    | 'Bead Blasted + Anodized type II (Glossy)'
    | 'Bead blasted'
    | 'Bead blasted + Anodized type II (Matte)'
    | 'Vapor smoothing'
    | 'Brushed + Anodized type II (Glossy)'
    | 'Fine machining (Ra 0.8μm / Ra 32μin)'
    | 'Brushed (Ra 1.2μm / Ra 47μin)'
    | 'Polishing (Ra 0.8μm / Ra 32μin)'
    | 'Standard (FDM)'
    | 'Brushed'
    | 'C-3 | Medium Brush Finish, 320 Grit Stone (Ra 0.63-0.70)'
    | 'D-3 | Rough Blast Finish, Blast #24 Oxide (Ra 3.2-18.0)'
    | 'Chromate Conversion Coating'
    | 'Bead Blasted + Anodized type II'
    | 'A-2 | High Gloss Finish, 3000 Grit Diamond Buff (Ra 0.025-0.050)'
    | 'Electroless Nickel Plating'
    | 'A-3 | Normal Gloss Finish, 12000 Grit Diamond Buff (Ra 0.05-0.10)'
    | 'As machined (Ra 3.2μm / Ra 126μin)'
    | 'As printed'
    | 'Brushed + Electropolished (Ra 0.8μm / Ra 32μin)'
    | 'As machined + Anodized type II'
    | 'Silk screening'
    | 'A-1 | High Gloss Finish, 6000 Grit Diamond Buff (Ra 0.012-0.025)'
    | 'Powder coated'
    | 'As machined + Anodized type III (Hardcoat)'
    | 'Black oxide'
    | 'Brushed + Anodized type II'
    | 'B-1 | Fine Brush Finish, 600 Grit Paper (Ra 0.05-0.010)'
    | 'Bead Blasted + Anodized type III (Hardcoat)'
    | 'B-2 | Fine Brush Finish, 400 Grit Paper (Ra 0.10-0.15)'
    | 'C-1 | Medium Brush Finish, 600 Grit Stone (Ra 0.35-0.40)'
    | 'C-2 | Medium Brush Finish, 400 Grit Stone (Ra 0.45-0.55)';
  color: 'No color' | 'Red' | 'Blue';
  partMarkings: 'No' | 'Yes';
  generalTolerance:
    | '±.020mm (±.001")'
    | '±.254mm (±.01")'
    | '±.030mm (±.001")'
    | '±.050mm (±.002")'
    | '±.075mm (±.003")'
    | '±.125mm (±.005")';
  tightestLinearTolerance: string;
  fits: 'No' | 'Yes';
  hasThreads: 'No' | 'Yes';
  internalCorners: 'Y' | 'N';
  technicalDrawing: 'Yes' | 'No';
  customRequirements: string;
  note: string;
}
